### ISSUE TITLE
missing activities results file for perturb-seq

### ISSUE THREAD

**Issue by alxndrkalinin** [broadinstitute/grit-benchmark#35]
[Table_S16_perturb-seq_screen_phenotypes.txt](https://github.com/broadinstitute/grit-benchmark/blob/33d0f86847b78dccd503aa962b58ee3330cf1eee/1.calculate-metrics/perturb-seq/scripts/nbconverted/0.calculate-grit-perturbseq.py#L59) that is used for id matching to compute Grit is missing and is not downloaded in [1.download-perturbseq](https://github.com/broadinstitute/grit-benchmark/blob/main/0.download-data/1.download-perturbseq.ipynb). I searched `GSE132080` folder on the FTP server, but couldn't find it there either.

@gwaybio do you rememeber where to get it?

**Comment by alxndrkalinin** [comment]
Nvm found it in the paper supplements

**Comment by gwaybio** [comment]
Nice catch! Yeah, we should definitely include this file to download
